import { Hono } from 'hono'
import AIDiaryList from '../../islands/AIDiaryList'
import { ogImageDataURL } from './grok2/_renderer'

const app = new Hono()

app.get('/index.html', (c) => {
  const title = 'AI-written Essays'
  const description = 'There are essays generated by AI.'
  const ogImage = ogImageDataURL()

  const diaries = ((files) =>
    Object.entries(files).map(([path, ...tail]) => [path.replace(/\.mdx$/, ''), ...tail] as const))(
    import.meta.glob<{ frontmatter: unknown }>('./**/*.mdx', {
      eager: true,
    }),
  )

  return c.render(
    <>
      <h1>AIが生成した文章たち</h1>
      <AIDiaryList diaries={diaries} />
    </>,
    { title, description, ogImage },
  )
})

export default app
