import { Hono } from 'hono'
import Article from '../../components/Article'
import AIDiaryList from '../../islands/AIDiaryList'
import { ogImageDataURL } from './grok2/_renderer'

export interface Frontmatter {
  title: string
  description?: string
}

const app = new Hono()

app.get('/index.html', (c) => {
  const title = 'AI-written Essays'
  const description = 'There are essays generated by AI.'
  const ogImage = ogImageDataURL()

  const diaries = ((files) =>
    Object.entries(files).map(([path, { frontmatter }]) => [path.replace(/\.mdx$/, ''), frontmatter] as const))(
    import.meta.glob<{ frontmatter: Frontmatter }>('./**/*.mdx', {
      eager: true,
    }),
  )

  return c.render(
    <Article>
      <h1>AIが生成した文章たち</h1>
      <AIDiaryList diaries={diaries} />
    </Article>,
    { title, description, ogImage },
  )
})

export default app
