import { Hono } from 'hono'
import AIDiaryList from '../../islands/AIDiaryList'
import type { Meta } from './type'

const diaries = ((files) =>
  Object.entries(files).map(([path, ...tail]) => [path.replace(/\.mdx$/, ''), ...tail] as const))(
  import.meta.glob<{ frontmatter: Meta }>('./**/*.mdx', {
    eager: true,
  }),
)

const app = new Hono()

app.get('/', (c) => {
  const title = 'AI-written Essays'
  const description = 'There are essays generated by AI.'

  return c.render(
    <>
      <h1>AIが生成した文章たち</h1>
      <AIDiaryList diaries={diaries} />
    </>,
    { title, description },
  )
})

export default app