name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Build
        run: make
      - if: failure()
        uses: ./.github/actions/notify-failure
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Check
        run: make check
      - if: failure()
        uses: ./.github/actions/notify-failure
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
