name: CI

on:
  push:
    branches:
      - source
  pull_request:
    branches:
      - source

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --omit dev --prefer-offline
      - name: Build
        run: npm run build
      - if: failure()
        uses: ./.github/actions/notify-failure
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --prefer-offline
      - name: Check
        run: npm run lint
      - if: failure()
        uses: ./.github/actions/notify-failure
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
