name: Prepare

on:
  workflow_call:
    secrets:
      RCLONE_CONFIG_BASE64:
        required: true
      SERVICE_ACCOUNT_KEY_JSON_BASE64:
        required: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Sync MDX files from Google Drive
        uses: ./.github/actions/sync-mdx-from-gdrive
        with:
          rclone-config: ${{ secrets.RCLONE_CONFIG_BASE64 }}
          service-account-file: ${{ secrets.SERVICE_ACCOUNT_KEY_JSON_BASE64 }}
      - name: Upload workspace
        uses: actions/upload-artifact@v7
        with:
          name: workspace
          path: '**/*.mdx'
